config/routes.rb
  devise_for :users, controllers: {invitations: 'invitations', registrations: 'registrations', passwords: 'passwords'}
  ActiveAdmin.routes(self)
  constraints DomainConstraint.new('bsqr1.com') do
    get '/:token', to: redirect { |path_params, req|
      "http://#{ENV['HOST']}/tracking_codes/#{path_params[:token]}"
    }
  end

  resources :tracking_codes do
    member do
      get :assign
      get :unassign
      get :unauthorized
    end
  end

  post 'tracking_ids/add_token', to: 'tracking_codes#add_token'

  #  zapier requests
  get '/zapier/sample_project', to: 'zapier#sample_project'
  get '/zapier/sample_video_view', to: 'zapier#sample_video_view'
  get '/zapier/sample_asset_reallocation', to: 'zapier#sample_asset_reallocation'
  get '/zapier/avaiable_on', to: 'zapier#sample_avaiable_on'
  get '/zapier/sample_maintenance', to: 'zapier#sample_maintenance_data'
  get '/zapier/sample_asset', to: 'zapier#sample_asset'
  get '/zapier/sample_marked_rental_or_public', to: 'zapier#sample_marked_rental_or_public'
  get '/zapier/sample_asset_remove_mp', to: 'zapier#sample_asset_remove_mp'
  get '/zapier/sample_route_stop', to: 'zapier#sample_route_stop'

  post '/zapier/create', to: 'zapier#create'
  post '/zapier/delete', to: 'zapier#destroy'

  get '/zapier/show', to: 'zapier#create_user'
  get '/lead/create', to: 'leads#create'
  post '/zapier/show', to: 'zapier#create_user'

  get '/zapier/update_hour_millage_asset', to: 'zapier#update_hour_millage_asset'
  post '/zapier/update_hour_millage_asset', to: 'zapier#update_hour_millage_asset'
  get '/zapier/update_lat_lng', to: 'zapier#update_lat_lng'
  post '/zapier/update_lat_lng', to: 'zapier#update_lat_lng'

  get 'assets/tokens', to: 'tracking_codes#get_tokens'
  post 'token/remove', to: 'tracking_codes#delete_token'
  post 'videos/add_video_usage', to: 'video_usages#add_video_usage'

  # Companies can only be created & deleted via /admin.
  resources :companies, only: [:show, :edit, :update] do
    resources :users, controller: 'company_assignments' do
      post :reinvite, to: 'company_assignments#reinvite_user'
      resources :project_assignments, controller: 'user_project_assignments', only: [:new, :create]
    end
  end

  get '/companies/:id/print_qr', to: 'companies#print_qr', as: 'print_company_qr'
  post '/companies/:id/qr_code_status', to: 'companies#qr_code_status', as: 'qr_code_status'
  post '/companies/:id/generate_printed_qr_codes', to: 'companies#generate_printed_qr_codes', as: 'generate_company_qr_codes'
  get '/companies/:id/download_printed_qr_codes', to: 'companies#download_printed_qr_codes', as: 'download_company_qr_codes'
  post '/companies/:id/email_printed_qr_codes', to: 'companies#email_printed_qr_codes', as: 'email_company_qr_codes'

  resources :projects, path: 'sites' do
    resources :assignments, controller: 'project_assignments', except: [:show, :edit]
    resources :csv_imports, controller: 'project_csv_imports', only: [:show, :create] do
      # No longer needed, as template is static; not generated dynamically anymore.
      # get :template, on: :collection
    end

    collection do
      post :upload_multiple
      get :search_by_name
    end
  end

  get '/assets/findit', to: 'assets#findit', :path => 'findit/inventory'
  get '/findit/checklist', to: 'assets#checklist'
  # get '/assets/get_assets_by_title', to: 'assets#get_assets_by_title'

  resources :assets do
    collection do
      put :update_multiple
      get :sold
      get :history_download
      get :search_by_title
    end

    member do
      patch :flag
      get :qr_scanning
      get :manage_inventory
      get :inventory_assets
      get :update_quantity
    end

    resources :marks, only: [:create, :destroy]
  end

  resources :groups do
    resources :csv_imports, controller: 'group_csv_imports', only: [:show, :create] do
    end
    collection do
      put :update_multiple
      post :upload_multiple
    end

    member do
      get :mark_as_closed
    end
  end
  resources :exports do
    collection do
      get :export_project
      get :export_assets
    end
  end

  resources :live_data, only: [:index] do
    collection do
      get :get_mqtt_token
      post :send_notification
      get '*path', action: :index
    end
  end

  resources :geo_fences do
  end

  resources :gauge_alerts do
    collection do
      get :search_assets_by_category
      get :category_assets
      get :asset_detail
      post :reset
    end
  end

  resources :exports, only: [:index, :show, :create]
  resources :news_items, only: [:index, :show], path: :newsroom

  get '/zip_validator' => 'maps#zip_validator', format: :json
  get '/zip_with_country_validator' => 'maps#zip_with_country_validator', format: :json
  get '/maps' => 'maps#index', :format => 'json'

  resources :wanted_assets, path: 'wanted', except: [:show] do
    collection do
      put :update_multiple
    end
  end

  post '/save_inventory', to: 'lists#save_inventory' , as: 'save_inventory'
  post '/save_checklist', to: 'lists#save_checklist' , as: 'save_checklist'
  get '/lists', to: 'lists#index' , as: 'lists'

  post '/get_asset', to: 'assets#asset'
  post 'reports/assets/generate', to: 'reports#generate_project_assets_report', as: 'reports_generate_project_assets_report'
  post 'reports/asset_location_audit/generate', to: 'reports#generate_asset_location_audit_report', as: 'reports_generate_asset_location_audit_report'
  get 'reports/:project_id/project_assets', to: 'reports#project_assets_report' , as: 'reports_project_assets_report'
  get 'reports', to: 'reports#index' , as: 'reports'
  #get 'csv_analytics', to: 'asset_reports#csv_analytics' , as: 'csv_analytics'

  get 'reports/assets', to: 'asset_reports#index', as: 'asset_reports'
  post 'reports/assets/filters', to: 'asset_reports#filter_post', as: 'asset_report_filter_post'
  get 'reports/assets/delete_myfilter/:id', to: 'asset_reports#delete_myfilter', as: 'asset_report_filter_delete'
  patch 'reports/assets/filters/:id', to: 'asset_reports#filter_patch', as: 'asset_report_filter_patch'
  get 'reports/assets/filters/:id', to: 'asset_reports#filter_get', as: 'asset_report_filter_get'
  get 'reports/assets/pre_filters/:key', to: 'asset_reports#pre_filter_get', as: 'asset_report_pre_filter_get'
  get 'reports/assets/download', to: 'asset_reports#download', as: 'asset_reports_download'
  patch 'reports/assets/filter_labels/:id', to: 'asset_reports#filter_label_patch', as: 'asset_report_filter_label_patch'
  post 'reports/assets/filter_labels', to: 'asset_reports#filter_label_post', as: 'asset_report_filter_label_post'

  get '/assets/:id/log_in', to: 'assets#log_in'
  get '/assets_versions/create'
  get '/user/profile' => 'profile#index'
  get '/dashboard' => 'dashboard#index'
  get '/marketplace' => 'marketplace#index'
  get '/favorites' => 'favorites#index'

  post '/update_cookies' => 'pages#update_cookies'

  get '/contact_us' => 'pages#contact_us'
  get '/terms' => 'pages#terms'
  get '/infringement_notice' => 'pages#infringement_notice'
  get '/privacy_policy' => 'pages#privacy_policy'
  get '/learn_more' => 'pages#learn_more'
  get '/market_place' => 'pages#market_place'
  get '/value' => 'pages#value'
  get '/industries_served' => 'pages#industries_served'
  get '/support' => 'pages#support'
  get '/learn_more' => 'pages#learn_more'
  get '/about_us' => 'pages#about_us'
  get '/reverse_geocode_map' => 'projects#reverse_geocode_map'

  post '/learn_more_mail' => 'pages#learn_more_email'
  post '/leads_mailer_mail' => 'pages#leads_mailer_email'

  # root 'pages#index'
  if Rails.env.development? || Rails.env.test?
    root to: 'pages#index'
  elsif Rails.env.staging? || Rails.env.production?
    root to: 'dashboard#index'
  end

  get '/robots', to: redirect('/robots.txt'), format: false
  get '/robots.:format' => 'robots#index'
  get '/resend_invitation' => 'companies#resend_invitation'
  resources :geo_positions, only: [:index]
  resources :clusters, only: [:index]
  resources :analytics, only: [:create] do
    collection do
      post :assets_filters
      post :asset_daily_filter
      post :more_most_recent
      post :asset_hour_filter
      post :asset_most_recent_filter
      get :search_groups_by_name
      get :search_users_by_name
      get :get_categories
      get :get_subcategories_by_category_id
      get :get_token_types
      get :get_analytic_filter_labels
    end
  end
  resources :map, only: [:index]

  resources :path_finder, only: [:index, :show, :create, :update] do
    get :show_multi, on: :collection
    post :route_history_search, on: :collection
    get :manage_routes, on: :collection
    # get :preview, on: :member
  end

  get '/route/:id/:fired_date', to: 'path_finder#show', as: 'route'
  get '/route_multi/:ids', to: 'path_finder#show_multi'
  get '/routes/search_by_name', to: 'path_finder#search_by_name'
  post '/path_finder/mark_as_done', to: 'path_finder#mark_as_done'
  post '/path_finder/mark_as_undone', to: 'path_finder#mark_as_undone'
  post '/path_finder/mark_all_as_undone', to: 'path_finder#mark_all_as_undone'
  post '/path_finder/send_route', to: 'path_finder#send_route'
  post '/path_finder/waypoint_options', to: 'path_finder#waypoint_options'
  post '/path_finder/project_assets/:id', to: 'path_finder#project_assets'
  post '/path_finder/:route_slug/:fired_date/preview', to: 'path_finder#preview', as: 'preview'
  get '/path_finder/:id/:fired_date/edit', to: 'path_finder#edit', as: 'path_finder_edit'
  get '/events', to: 'events#index', as: 'event_index'
  get '/events/db_action', to: 'events#db_action', as: 'event_action'
  get '/events/asset/:asset_id', to: 'events#index', as: 'event_asset'
  get '/events/:event_id', to: 'events#index', as: 'event'
  get '/users/search_by_name', to: 'users#search_by_name'
  get '/move_inventory', to: 'assets#move_inventory'
  get '/safety_reports/get_scorecard', to: 'safety_reports#get_scorecard'

app/models/company.rb
class Company < ActiveRecord::Base
  mount_uploader :company_logo, CompanyLogoUploader

  after_create :allocate_tracking_codes,:create_by_default_on_subscriptions

  belongs_to :contact, class_name: 'User', dependent: :delete
  accepts_nested_attributes_for :contact

  has_many :users, -> { where(deleted_at: nil) }, dependent: :delete_all
  has_many :projects
  has_many :assets
  has_many :equipments
  has_many :wanted_assets
  has_many :groups
  has_one :address, as: :addressable, dependent: :destroy
  belongs_to :project, dependent: :destroy
  has_many :subscriptions
  has_many :routes
  has_many :tracking_codes
  has_many :geo_fences
  has_many :analytic_filter_labels

  accepts_nested_attributes_for :address, allow_destroy: true
  accepts_nested_attributes_for :project

  validates :name, :address, :contact_id, presence: true
  validates :admin_seats, numericality: {only_integer: true, greater_than: 0}, allow_blank: true
  validates :contact_id, inclusion: {in: ->(record) { record.users.ids }, message: 'is not in the same company'}, unless: 'contact.blank?'

  validates :website, url: {allow_blank: true}

  validates :name, uniqueness: {scope: :region, message: 'already exists'}

  enum company_type: %w(client demo)
  enum qr_status: %w(not_requested requested in_progress created downloaded)
  enum qr_print_type: ['laserPrint', 'thermalPrint']
  enum qr_format: ['4_x_1', '4_x_2', '4_x_2.5', '4_x_3', '4_x_4',
                 'avery_5160', 'avery_5163', 'avery_5963', 'avery_6572', 'avery_6871']

  def admin_seats_remaining
    if admin_seats.present?
      admin_seats - users.company_admin.count
    end
  end

  def create_by_default_on_subscriptions
    Subscription.create([{company_id: self.id, category: 'wantit',state: 'active',payment: true},
      {company_id: self.id, category: 'company reports',state: 'active',payment: true},
      {company_id: self.id, category: 'add tracking to asset',state: 'active',payment: true},
      {company_id: self.id, category: 'maintenance',state: 'active',payment: true}])
  end

  def qr_requested_or_generating?
    qr_status.in? ["requested", "in_progress"]
  end

  def total_codes_to_create
    TrackingCode::MAX_UNUSED_CODES - total_unused_codes
  end

  def allocate_tracking_codes
    tokens = []
    self.total_codes_to_create.times do
      uuid = SecureRandom.uuid
      uuid = uuid.gsub!('-', '')
      str = Base64.encode64([uuid].pack('H*'))[0..21]
      str = str.gsub('+', '-')
      str = str.gsub('/', '~')
      tokens << str
    end
    TrackingCode.transaction do
      tokens.each do |token|
        self.tracking_codes.create(token: token)
      end
    end
  end

  def total_unused_codes
    tracking_codes.unassigned.count
  end

  def total_used_codes
    tracking_codes.assigned.count
  end

  def company_admins
    users.where(role: User.roles[:company_admin])
  end

  def field_members
    users.where(role: User.roles[:field_member])
  end

  def can_create_exports?
    self.projects.any? or self.assets.any?
  end

  def can_be_destroyed?
    assets.empty? and wanted_assets.empty? and groups.empty? and ( projects.empty? ||  (projects.count == 1 and projects.first == self.project))
  end

  # Disables/enables all users of a company when their company gets changed from active/inactive
  def update_active_state!
    if previous_changes[:active].present?
      if active?
        users.update_all(active: true)
      else
        users.update_all(active: false)
      end
    end
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  HISTORY_FIELDS = %w{ name notes group_num client description state project_id}.freeze
  HISTORY_STRING_NIL_CHECK_FIELDS = %w{notes group_num client description}.freeze

  belongs_to :project
  belongs_to :company
  validates :name, :company, :project, presence: true
  has_many :assets, dependent: :nullify
  has_many :csv_imports, dependent: :destroy

  # Update Elasticsearch index on group save
  update_index('groups#group') { self }

  # This callback is used to create version for assets
  after_save :create_version, :change_assets_project
  scope :available, ->{ where(deleted_at: nil).where.not(state: 'closed').order(:name) }

  def project_name
    if company.present? && project.present? && project.company == company
      project.name
    end
  end

  # instead of deleting, indicate the user requested a delete & timestamp it
  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end

  def total_assets_count
    assets.not_sold_deleted.count
  end

  def total_assets_value
    assets.not_sold_deleted.sum(:price)
  end

  def change_assets_project
    # if update and project_id is changed
    if !self.id_changed? && self.changes.key?('project_id')
      Asset.transaction do
        self.assets.not_sold_deleted.each do |asset|
          asset.update(
            project_id: self.project_id,
            zip_code_id: ZipCode.find_or_create_by(zip_code: self.project.address.zip).id
          )
        end
      end
    end
  end

  def create_version
    # Find current logged in user id
    current_user_id = User.current.try(:id)
    action = self.id_changed? ? 'create' : 'update'

    GroupsVersion.transaction do
      if action == 'create'
        GroupsVersion.create!(group_id: self.id, field_name: 'newly_created', from: '', to: '',
            user_id: current_user_id, company_id: self.company_id, action: action)
      end
      self.changes.each do |field_name, field_value|
        if Group::HISTORY_FIELDS.include? field_name
          if not ((Group::HISTORY_STRING_NIL_CHECK_FIELDS.include? field_name) && field_value[0].blank? && field_value[1].blank?)
            GroupsVersion.create!(group_id: self.id, field_name: field_name, from: field_value[0], to: field_value[1],
              user_id: current_user_id, company_id: self.company_id, action: action)
          end
        end
      end
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  # Used for bulk action drop-down menu
  def group_actions_for_user(user)
    actions = [
      ['Move', 'move'],
      ['Mark as Closed', 'mark_as_closed'],
      ['Delete', 'delete']
    ]
    if @group_filter_search.is_closed?
      actions.delete(['Mark as Closed', 'mark_as_closed'])
    end

    actions
  end

  def group_version_action_label(version)
    if version.field_name == 'project_id'
      'Group Moved'
    elsif version.field_name == 'notes'
      'Notes changed'
    elsif version.field_name == 'asset_id'
      if version.action == 'delete'
        'Asset Unlinked'
      else
        'Asset Linked'
      end
    else
      version.field_name.underscore.humanize
    end
  end

  def group_version_value(version, f)
    value = version.try(f.to_sym)
    if version.field_name == 'project_id'
      Project.find_by_id(value).try(:name)
    elsif version.field_name == 'asset_id'
      Asset.find_by_id(value).try(:title)
    else
      value
    end
  end
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs row separator-row">
      <div class="col s12 m6 form-col">
        <div class="row">
          <%= f.input :name, autofocus: true, required: true, wrapper_html: {class: 'col s12'} %>
        </div>

        <div class="row">
          <%= f.input :group_num, label: 'ID/Number', wrapper_html: {class: 'col s12'} %>
        </div>

        <div class="row">
          <%= f.input :client, wrapper_html: {class: 'col s12'} %>
        </div>

        <div class="row">
           <span style="padding-left: 5px;">Select Site</span>
          <%= f.association :project, required: false, collection: @projects.available, include_blank: (@group.new_record?) ? ' ' : false, input_html: {class: 'select2 '}, selected: (@group.new_record?) ? ' ' : @group.project_id, wrapper_html: {class: 'select-project'} %>
          <%= render partial: 'modal_move_edit', locals: { group: @group } %>
        </div>
      </div>

      <div class="col s12 m6 form-col">
        <div class="row">
          <%= f.input :description, as: :material_text, wrapper_html: {class: 'col s12'} %>
        </div>

        <div class="row">
          <%= f.input :notes, as: :material_text, wrapper_html: {class: 'col s12'} %>
        </div>
      </div>
    </div>

    <div class="form-actions">
      <%= f.button :button, onClick: "ga('send', 'Internal Link', 'Projects: #{action_name}');".html_safe, data: {disable_with: 'Processing…'} %>
    </div>
<% end %>

app/views/groups/_group.html.erb
<% if group !=nil %>
<tr id="<%= dom_id group.becomes(Group) %>">
   <td class="selection-cell <%=params[:controller] == 'projects' ? 'group-chkbox-align' : ''%>">

      <%= check_box_tag "group-selected-#{group.id}", nil, false, class: 'filled-in', data: { id: group.id, count: group.assets.available.count } %>
      <%= content_tag :label, nil, for: "group-selected-#{group.id}" %>

  </td>
  <td>
    <%= link_to group do %>
        <p class="group_nam h2"><%= group.name %></p>
        <% if group.project_name.present?%>
          <p class="categor subh1"><%= group.project_name %></p>
        <% end %>
        <% if group.group_num.present? %>
            <p class="project_project_num">Group Num: <%= group.group_num %></p>
        <% end %>
        <p class="description">
          Total Assets: <%= group.assets.not_sold_deleted.count %>
        </p>
        <p class="date_posted">Created: <%= format_date(group.created_at) %></p>
    <% end %>
  </td>
</tr>
<% end %>

app/views/groups/_list.html.erb
<% redirect_path ||= '' %>
  <div id="panel-list" class="card-panel" style="top: 0px">
    <div class="card-panel-heading mb-sm pb-mn" id="candice-cobb-s-route">
      <div class="row mb-tn">
        <div class="col s12 m6 l6">
          <%if params[:controller] == 'projects'%>
            <div class="card-panel-heading without-border h1">Groups</div>
          <%else%>
            <div class="h1">Groups</div>
          <%end%>
        </div>
        <div class="col s12 m6 l6 right-align">
          <div class="project-header-icons">
            <% if current_page?(groups_path) %>
              <%= link_to   "#{ image_tag('guide_download_blue.png', alt: 'User Guide')}<span>User<br />Guide</span>".html_safe, '//s3.amazonaws.com/buildsourced-production-1/how_to_mass_import_groups.pdf', target: '_blank' %>
              <%= link_to   "#{ image_tag('XLS_download_artwork.png', alt: 'Site Template')}<span>Group<br />Template</span>".html_safe, '//s3.amazonaws.com/buildsourced-production-1/groups_inventory_capture_sheet.csv', target: '_blank' %>

              <a class="" id="bulk-group-upload-modal-open" href="#bulk-group-upload-modal">
                <i class="icon-upload" ></i>
                <span >Import<br /> Group</span>
              </a>
            <% end %>
          </div>
        </div>
        <div class="col s12 ">
          <div class="filter-header">
          </div>
        </div>
      </div>
      <div class="row margin-bottom-0 mt-mn">
        <div class="col s6 m6 l4 ">
          <div class="action-filter-form-container">
            <div class="all-select-wrapper radio-btn">
              <%= check_box_tag 'group-select-toggle', nil, false, class: 'filled-in radio-btn' %>
              <%= content_tag :label, nil, for: 'group-select-toggle' %>
            </div>
            <%= form_tag form_path, class: 'action-filter-form', method: :put do %>
                  <div class="select-wrapper">
                    <a class="dropdown-button action-border <%= params[:controller] == 'projects' ? 'new-action-caret-groups dd1-caret' : ' '%>" href="#" data-activates="group-action-dropdown" data-constrainwidth="false">
                      Actions
                      <span class="caret">▼</span>
                    </a>
                  </div>

              <ul id="group-action-dropdown" class="dropdown-content">
                <% group_actions_for_user(current_user).each do |action| %>
                  <li><span class="groups-header-action" href="#" data-action="<%= action[1] %>"><%= action[0] %></span></li>
                <% end %>
              </ul>

              <%= hidden_field_tag :group_action %>
              <%= hidden_field_tag :group_ids %>
              <%= hidden_field_tag :redirect_to, redirect_path %>
              <%= render partial: 'groups/modal_reallocate_index' %>
              <%= render partial: 'shared/modal_select_group_error' %>
            <% end %>
          </div>
        </div>
        <div class="col s6 m6 l8 right-align ">
          <div class="filter-list">
            <div class="show-box filter-item">
              <%= render partial: 'shared/group_page_size_form' %>
            </div>
            <div class="srch-name filter-item">
              <%= form_tag '', class: 'filter-form', method: :get do %>
                <%= select_tag :sort, options_for_select(GroupSearch.sorts.keys.map { |s| [s.to_s.titleize, s] }, @group_filter_search ? @group_filter_search.sort : nil), id: 'group-header-sort' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
    <table id="table-groups" class="table tblsgroups" style="">
      <% if groups.size > 0 %>
        <%= render partial: 'groups/group', collection: groups %>
      <% else %>
        <p>No Groups Found</p>
      <% end %>

      <% if groups.total_pages > 1 %>
        <tr>
          <td class="hide-on-small-and-down" colspan= "2">
            <%= paginate groups, :param_name => page_param.to_sym %>
          </td>
          <td class="hide-on-med-and-up" colspan= "2">
            <%= paginate groups, :param_name => page_param.to_sym, window: 2 %>
          </td>
        </tr>
      <% end %>
    </table>

  </div>

app/views/groups/_modal_move_edit.html.erb
<div id="modal-group-edit" class="modal">
  <div class="modal-content">
    <h4>Move Group</h4>
    <div class="row" id="group-edit-notes">
      <p>If you move this group, all assets in the group will have their longitude and latitude updated to match the site location.</p>
    </div>
    <br><a href="#!" class="modal-action modal-close waves-effect btn select-increment-reallocation">OK</a>
  </div>
</div>

app/views/groups/_modal_reallocate_index.html.erb
<div id="reallocate-group" class="modal">
  <div class="modal-content">
    <div class="card-panel-heading h1 pb-tn">Move Group</div>
    <div class="row">
      <div class="col s12">
        <p class="select-label2">Site</p>
        <%= select_tag :project_id, options_from_collection_for_select(@projects.available, :id, :name, @groups.first.try(:project_id)), class: 'browser-default select2' %>
      </div>
    </div>
  <div class="row">
    <div class="col s12 right-align">
      <a href="#!" class="modal-action modal-close btn but2 white">Cancel</a>
      <%= button_tag 'Move Group', class: 'alternate-option btn', onClick: "ga('send', 'Internal Link', 'Move group');".html_safe %>
    </div>
    </div>
  </div>
</div>

app/views/groups/_upload_spreadsheet.html.erb
<div id="modal-upload-spreadsheet" class="modal">
  <div class="modal-content modal-bg-clr">
    <div class="card-panel-heading h1 pb-tn">Import Assets</div>
    <%= render partial: "group_csv_imports/form" %>
  </div>
</div>

app/views/groups/index.html.erb
<%= render partial: 'shared/group_search', locals: { groups: @groups } %>

<div class="row">
  <div id="filters" class="col s12 m12 l4">
    <div class="card-panel">
      <div class="header-link">
        <h1 class="h1 panel-bdr">Filters</h1>
      </div>
      <%= simple_form_for(@group_filter_search, url: '',method: :get) do |f| %>
        <%= f.input :query, as: :hidden %>
        <%= f.input :sort, as: :hidden %>
        <%= f.input :page_size, as: :hidden %>

        <div class="form-inputs row group-filter">
          <%= f.input :is_active, as: :boolean, boolean_style: :inline, label: 'Active Groups', wrapper_html: {class: 'col s12'}, input_html: {class: 'filled-in'},label_html: {class: 'cb1'} %>
          <%= f.input :is_closed, as: :boolean, boolean_style: :inline, label: 'Closed Groups', wrapper_html: {class: 'col s12'}, input_html: {class: 'filled-in'},label_html: {class: 'cb1'} %>

          <% if !current_user.company.project.blank? %>
            <%= f.input :default_project, as: :boolean, boolean_style: :inline, label: 'Default Site', wrapper_html: {class: 'col s12 dd1'}, input_html: {class: 'filled-in'},label_html: {class: 'cb1'} %>
          <% end %>

          <%= f.input :project, collection: current_user.company.projects.available.order(:name).pluck(:name, :id), label: 'Site', include_blank: 'Any Site', wrapper_html: {class: 'col s12'}, input_html: {class: 'select2'},label_html: {class: 'cb1'} %>

        </div>

        <div class="form-actions">
          <%= link_to 'Reset', groups_path, class: 'waves-effect waves-light btn white but2' %>
          <%= f.button :button, 'Apply Filters',class: 'but1' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col s12 m12 l8">
    <%= render partial: 'groups/list',
      locals: {
        groups: @groups,
        redirect_path: groups_path,
        form_path: update_multiple_groups_path,
        page_param: 'page' }
    %>
  </div>
</div>
<!-- Modal bulk upload groups -->
<div id="bulk-group-upload-modal" class="modal">
  <div class="modal-content">
    <div class="card-panel-heading h1 pb-tn">Import Groups</div>
    <div>
      <%= form_tag upload_multiple_groups_path, multipart: true do %>
        <div class="file-field input-field">
          <div class="btn">
            <span class = "import-projects-file-btn">File</span>
            <%= file_field_tag :file, accept: 'text/csv' , required: true %>
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
          </div>
        </div>
        <div class="form-actions project-import-btn">
          <a href="#!" class="modal-action modal-close btn but2 white">Cancel</a>
          <%= submit_tag "Import" ,:class =>"btn" , data: {disable_with: 'Processing Data...'}%>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= fab Group %>