config/routes.rb
Rails.application.routes.draw do
  resources :company_safety_configurations
  get 'safety_reports/landing_page'

  require 'sidekiq/web'

  mount Sidekiq::Web, at: '/sidekiq'
  mount ZapierRestHooks::Engine, at: '/hooks'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {invitations: 'invitations', registrations: 'registrations', passwords: 'passwords'}
  ActiveAdmin.routes(self)
  constraints DomainConstraint.new('bsqr1.com') do
    get '/:token', to: redirect { |path_params, req|
      "http://#{ENV['HOST']}/tracking_codes/#{path_params[:token]}"
    }
  end

  resources :tracking_codes do
    member do
      get :assign
      get :unassign
      get :unauthorized
    end
  end

  post 'tracking_ids/add_token', to: 'tracking_codes#add_token'

  #  zapier requests
  get '/zapier/sample_project', to: 'zapier#sample_project'
  get '/zapier/sample_video_view', to: 'zapier#sample_video_view'
  get '/zapier/sample_asset_reallocation', to: 'zapier#sample_asset_reallocation'
  get '/zapier/avaiable_on', to: 'zapier#sample_avaiable_on'
  get '/zapier/sample_maintenance', to: 'zapier#sample_maintenance_data'
  get '/zapier/sample_asset', to: 'zapier#sample_asset'
  get '/zapier/sample_marked_rental_or_public', to: 'zapier#sample_marked_rental_or_public'
  get '/zapier/sample_asset_remove_mp', to: 'zapier#sample_asset_remove_mp'
  get '/zapier/sample_route_stop', to: 'zapier#sample_route_stop'

  post '/zapier/create', to: 'zapier#create'
  post '/zapier/delete', to: 'zapier#destroy'

  get '/zapier/show', to: 'zapier#create_user'
  get '/lead/create', to: 'leads#create'
  post '/zapier/show', to: 'zapier#create_user'

  get '/zapier/update_hour_millage_asset', to: 'zapier#update_hour_millage_asset'
  post '/zapier/update_hour_millage_asset', to: 'zapier#update_hour_millage_asset'
  get '/zapier/update_lat_lng', to: 'zapier#update_lat_lng'
  post '/zapier/update_lat_lng', to: 'zapier#update_lat_lng'

  get 'assets/tokens', to: 'tracking_codes#get_tokens'
  post 'token/remove', to: 'tracking_codes#delete_token'
  post 'videos/add_video_usage', to: 'video_usages#add_video_usage'

  # Companies can only be created & deleted via /admin.
  resources :companies, only: [:show, :edit, :update] do
    resources :users, controller: 'company_assignments' do
      post :reinvite, to: 'company_assignments#reinvite_user'
      resources :project_assignments, controller: 'user_project_assignments', only: [:new, :create]
    end
  end

  get '/companies/:id/print_qr', to: 'companies#print_qr', as: 'print_company_qr'
  post '/companies/:id/qr_code_status', to: 'companies#qr_code_status', as: 'qr_code_status'
  post '/companies/:id/generate_printed_qr_codes', to: 'companies#generate_printed_qr_codes', as: 'generate_company_qr_codes'
  get '/companies/:id/download_printed_qr_codes', to: 'companies#download_printed_qr_codes', as: 'download_company_qr_codes'
  post '/companies/:id/email_printed_qr_codes', to: 'companies#email_printed_qr_codes', as: 'email_company_qr_codes'

  resources :projects, path: 'sites' do
    resources :assignments, controller: 'project_assignments', except: [:show, :edit]
    resources :csv_imports, controller: 'project_csv_imports', only: [:show, :create] do
      # No longer needed, as template is static; not generated dynamically anymore.
      # get :template, on: :collection
    end

    collection do
      post :upload_multiple
      get :search_by_name
    end
  end

  get '/assets/findit', to: 'assets#findit', :path => 'findit/inventory'
  get '/findit/checklist', to: 'assets#checklist'
  # get '/assets/get_assets_by_title', to: 'assets#get_assets_by_title'

  resources :assets do
    collection do
      put :update_multiple
      get :sold
      get :history_download
      get :search_by_title
    end

    member do
      patch :flag
      get :qr_scanning
      get :manage_inventory
      get :inventory_assets
      get :update_quantity
    end

    resources :marks, only: [:create, :destroy]
  end

  resources :groups do
    resources :csv_imports, controller: 'group_csv_imports', only: [:show, :create] do
    end
    collection do
      put :update_multiple
      post :upload_multiple
    end

    member do
      get :mark_as_closed
    end
  end
  resources :exports do
    collection do
      get :export_project
      get :export_assets
    end
  end

  resources :live_data, only: [:index] do
    collection do
      get :get_mqtt_token
      post :send_notification
      get '*path', action: :index
    end
  end

  resources :geo_fences do
  end

  resources :gauge_alerts do
    collection do
      get :search_assets_by_category
      get :category_assets
      get :asset_detail
      post :reset
    end
  end

  resources :exports, only: [:index, :show, :create]
  resources :news_items, only: [:index, :show], path: :newsroom

  get '/zip_validator' => 'maps#zip_validator', format: :json
  get '/zip_with_country_validator' => 'maps#zip_with_country_validator', format: :json
  get '/maps' => 'maps#index', :format => 'json'

  resources :wanted_assets, path: 'wanted', except: [:show] do
    collection do
      put :update_multiple
    end
  end

  post '/save_inventory', to: 'lists#save_inventory' , as: 'save_inventory'
  post '/save_checklist', to: 'lists#save_checklist' , as: 'save_checklist'
  get '/lists', to: 'lists#index' , as: 'lists'

  post '/get_asset', to: 'assets#asset'
  post 'reports/assets/generate', to: 'reports#generate_project_assets_report', as: 'reports_generate_project_assets_report'
  post 'reports/asset_location_audit/generate', to: 'reports#generate_asset_location_audit_report', as: 'reports_generate_asset_location_audit_report'
  get 'reports/:project_id/project_assets', to: 'reports#project_assets_report' , as: 'reports_project_assets_report'
  get 'reports', to: 'reports#index' , as: 'reports'
  #get 'csv_analytics', to: 'asset_reports#csv_analytics' , as: 'csv_analytics'

  get 'reports/assets', to: 'asset_reports#index', as: 'asset_reports'
  post 'reports/assets/filters', to: 'asset_reports#filter_post', as: 'asset_report_filter_post'
  get 'reports/assets/delete_myfilter/:id', to: 'asset_reports#delete_myfilter', as: 'asset_report_filter_delete'
  patch 'reports/assets/filters/:id', to: 'asset_reports#filter_patch', as: 'asset_report_filter_patch'
  get 'reports/assets/filters/:id', to: 'asset_reports#filter_get', as: 'asset_report_filter_get'
  get 'reports/assets/pre_filters/:key', to: 'asset_reports#pre_filter_get', as: 'asset_report_pre_filter_get'
  get 'reports/assets/download', to: 'asset_reports#download', as: 'asset_reports_download'
  patch 'reports/assets/filter_labels/:id', to: 'asset_reports#filter_label_patch', as: 'asset_report_filter_label_patch'
  post 'reports/assets/filter_labels', to: 'asset_reports#filter_label_post', as: 'asset_report_filter_label_post'

  get '/assets/:id/log_in', to: 'assets#log_in'
  get '/assets_versions/create'
  get '/user/profile' => 'profile#index'
  get '/dashboard' => 'dashboard#index'
  get '/marketplace' => 'marketplace#index'
  get '/favorites' => 'favorites#index'

  post '/update_cookies' => 'pages#update_cookies'

  get '/contact_us' => 'pages#contact_us'
  get '/terms' => 'pages#terms'
  get '/infringement_notice' => 'pages#infringement_notice'
  get '/privacy_policy' => 'pages#privacy_policy'
  get '/learn_more' => 'pages#learn_more'
  get '/market_place' => 'pages#market_place'
  get '/value' => 'pages#value'
  get '/industries_served' => 'pages#industries_served'
  get '/support' => 'pages#support'
  get '/learn_more' => 'pages#learn_more'
  get '/about_us' => 'pages#about_us'
  get '/reverse_geocode_map' => 'projects#reverse_geocode_map'

  post '/learn_more_mail' => 'pages#learn_more_email'
  post '/leads_mailer_mail' => 'pages#leads_mailer_email'

  # root 'pages#index'
  if Rails.env.development? || Rails.env.test?
    root to: 'pages#index'
  elsif Rails.env.staging? || Rails.env.production?
    root to: 'dashboard#index'
  end

  get '/robots', to: redirect('/robots.txt'), format: false
  get '/robots.:format' => 'robots#index'
  get '/resend_invitation' => 'companies#resend_invitation'
  resources :geo_positions, only: [:index]
  resources :clusters, only: [:index]
  resources :analytics, only: [:create] do
    collection do
      post :assets_filters
      post :asset_daily_filter
      post :more_most_recent
      post :asset_hour_filter
      post :asset_most_recent_filter
      get :search_groups_by_name
      get :search_users_by_name
      get :get_categories
      get :get_subcategories_by_category_id
      get :get_token_types
      get :get_analytic_filter_labels
    end
  end
  resources :map, only: [:index]

  resources :path_finder, only: [:index, :show, :create, :update] do
    get :show_multi, on: :collection
    post :route_history_search, on: :collection
    get :manage_routes, on: :collection
    # get :preview, on: :member
  end

  get '/route/:id/:fired_date', to: 'path_finder#show', as: 'route'
  get '/route_multi/:ids', to: 'path_finder#show_multi'
  get '/routes/search_by_name', to: 'path_finder#search_by_name'
  post '/path_finder/mark_as_done', to: 'path_finder#mark_as_done'
  post '/path_finder/mark_as_undone', to: 'path_finder#mark_as_undone'
  post '/path_finder/mark_all_as_undone', to: 'path_finder#mark_all_as_undone'
  post '/path_finder/send_route', to: 'path_finder#send_route'
  post '/path_finder/waypoint_options', to: 'path_finder#waypoint_options'
  post '/path_finder/project_assets/:id', to: 'path_finder#project_assets'
  post '/path_finder/:route_slug/:fired_date/preview', to: 'path_finder#preview', as: 'preview'
  get '/path_finder/:id/:fired_date/edit', to: 'path_finder#edit', as: 'path_finder_edit'
  get '/events', to: 'events#index', as: 'event_index'
  get '/events/db_action', to: 'events#db_action', as: 'event_action'
  get '/events/asset/:asset_id', to: 'events#index', as: 'event_asset'

app/models/company.rb
class Company < ActiveRecord::Base
  mount_uploader :company_logo, CompanyLogoUploader

  after_create :allocate_tracking_codes,:create_by_default_on_subscriptions

  belongs_to :contact, class_name: 'User', dependent: :delete
  accepts_nested_attributes_for :contact

  has_many :users, -> { where(deleted_at: nil) }, dependent: :delete_all
  has_many :projects
  has_many :assets
  has_many :equipments
  has_many :wanted_assets
  has_many :groups
  has_one :address, as: :addressable, dependent: :destroy
  belongs_to :project, dependent: :destroy
  has_many :subscriptions
  has_many :routes
  has_many :tracking_codes
  has_many :geo_fences
  has_many :analytic_filter_labels

  accepts_nested_attributes_for :address, allow_destroy: true
  accepts_nested_attributes_for :project

  validates :name, :address, :contact_id, presence: true
  validates :admin_seats, numericality: {only_integer: true, greater_than: 0}, allow_blank: true
  validates :contact_id, inclusion: {in: ->(record) { record.users.ids }, message: 'is not in the same company'}, unless: 'contact.blank?'

  validates :website, url: {allow_blank: true}

  validates :name, uniqueness: {scope: :region, message: 'already exists'}

  enum company_type: %w(client demo)
  enum qr_status: %w(not_requested requested in_progress created downloaded)
  enum qr_print_type: ['laserPrint', 'thermalPrint']
  enum qr_format: ['4_x_1', '4_x_2', '4_x_2.5', '4_x_3', '4_x_4',
                 'avery_5160', 'avery_5163', 'avery_5963', 'avery_6572', 'avery_6871']

  def admin_seats_remaining
    if admin_seats.present?
      admin_seats - users.company_admin.count
    end
  end

  def create_by_default_on_subscriptions
    Subscription.create([{company_id: self.id, category: 'wantit',state: 'active',payment: true},
      {company_id: self.id, category: 'company reports',state: 'active',payment: true},
      {company_id: self.id, category: 'add tracking to asset',state: 'active',payment: true},
      {company_id: self.id, category: 'maintenance',state: 'active',payment: true}])
  end

  def qr_requested_or_generating?
    qr_status.in? ["requested", "in_progress"]
  end

  def total_codes_to_create
    TrackingCode::MAX_UNUSED_CODES - total_unused_codes
  end

  def allocate_tracking_codes
    tokens = []
    self.total_codes_to_create.times do
      uuid = SecureRandom.uuid
      uuid = uuid.gsub!('-', '')
      str = Base64.encode64([uuid].pack('H*'))[0..21]
      str = str.gsub('+', '-')
      str = str.gsub('/', '~')
      tokens << str
    end
    TrackingCode.transaction do
      tokens.each do |token|
        self.tracking_codes.create(token: token)
      end
    end
  end

  def total_unused_codes
    tracking_codes.unassigned.count
  end

  def total_used_codes
    tracking_codes.assigned.count
  end

  def company_admins
    users.where(role: User.roles[:company_admin])
  end

  def field_members
    users.where(role: User.roles[:field_member])
  end

  def can_create_exports?
    self.projects.any? or self.assets.any?
  end

  def can_be_destroyed?
    assets.empty? and wanted_assets.empty? and groups.empty? and ( projects.empty? ||  (projects.count == 1 and projects.first == self.project))
  end

  # Disables/enables all users of a company when their company gets changed from active/inactive
  def update_active_state!
    if previous_changes[:active].present?
      if active?
        users.update_all(active: true)
      else
        users.update_all(active: false)
      end
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  include TrackingCodesHelper
  before_action :authenticate_user!
  load_and_authorize_resource

  def show
    @company_users = @company.users.where('role in  (?)', [0,1, 4]).page(params[:c_page])
    @project_users = @company.users.where.not('role in (?)', [0, 1, 4]).page(params[:p_page])
  end

  def edit
  end

  def print_qr
  end

  def download_printed_qr_codes
    if params.has_key? 'label_file_name'
      if Rails.env.development?
        if File.exists? qr_codes_file_path(@company.id, params['label_file_name'])
          send_file(qr_codes_file_path(@company.id, params['label_file_name']),
            filename: qr_codes_file_name(@company.id, params['label_file_name']),
            :type => 'application/pdf',
            :disposition => 'attachment' )
        else
          flash[:error] = 'QR codes you are trying to access does not exist.'
          redirect_to print_company_qr_path(@company)
        end
      else
        obj = S3_OBJECT.object(qr_codes_file_path(@company.id, params[:label_file_name]))
        if obj.exists?
          data = open(obj.presigned_url(:get, expires_in: 60 * 60))
          send_data data.read, filename: "#{qr_codes_file_name(@company.id, params[:label_file_name])}", type: 'application/pdf', :x_sendfile => true
        else
          flash[:error] = 'QR codes you are trying to access does not exist.'
          redirect_to print_company_qr_path(@company)
        end
      end
    else
      flash[:error] = 'File label is not specified.'
      redirect_to print_company_qr_path(@company)
    end
  end

  def email_printed_qr_codes
    response = Hash.new

    file_obj = Rails.env.development? ? (File.exists? qr_codes_file_path(@company.id, params['label_format'])) : S3_OBJECT.object(qr_codes_file_path(@company.id, params['label_format'])).exists?
    company = current_user.company
    @company_tracking_subscription = company.subscriptions.where(category: 'add tracking to asset',state: 'active',payment: true).first
    if file_obj and @company_tracking_subscription.present?
      if TrackingCodeMailer.send_generated_qr_codes(current_user.email, qr_codes_file_name(@company.id, params['label_format']), @company.id, params['label_format']).deliver
        response = get_response(params[:action], 'success')
      else
        response = get_response(params[:action], 'failed')
      end
    else
      response = get_response(params[:action], 'not_generated')
    end
    respond_to do |format|
      format.json { render json: response }
    end
  end

  def generate_printed_qr_codes
    @company.allocate_tracking_codes
    response = Hash.new
    if (valid_label_and_print_type)
      if GenerateQrCodesJob.perform_later(@company.id, params[:label_format])
        @company.update(qr_status: 'requested', qr_print_type: params['printedType'], qr_format: params[:label_format])
        response = get_response(params[:action], 'generating')
      else
        response = get_response(params[:action], 'failed')
      end
    else
      response = get_response(params[:action], 'invalid_print_or_label')
    end
    respond_to do |format|
      format.json { render json: response }
    end
  end

  def qr_code_status
    response = Hash.new
    if @company.qr_status == 'created'
      response[:status] = true
      response[:used_codes_count] = @company.total_used_codes
      response[:unused_codes_count] = @company.total_unused_codes
    else
      response[:status] = false
    end
    return render json: response
  end

  def update
    @company.update(company_params)
    respond_with @company
  end

  def resend_invitation
    user = User.find(params[:format])
    user.invite!(current_user)
    redirect_to company_path(current_user.company.id), notice: 'Re-invitation email sent successfully.'
  end

  def valid_label_and_print_type
    if ((params.has_key? 'printedType') && (params.has_key? 'label_format'))
      if is_valid_print_type_and_label params['printedType'], params['label_format']
        true
      end
    end
  end

  private

  def company_params
    params.require(:company).permit(:name, :company_logo, :remove_company_logo, :region, :website, :contact_id, address_attributes: [:id, :line_1, :line_2, :city, :state, :zip])
  end
end

app/views/companies/_directory.html.erb
<div class="row">
  <div class="col s12 m12 l6">
    <div class="card-panel">
      <h1 class="card-panel-heading h1">Company Wide</h1>
      <table class="company_directory striped">
        <thead class="header-h3b b21">
          <tr>
            <th>Name</th>
            <th>Role</th>
          </tr>
        </thead>
        <tbody>
          <% @company_users.order(:last_name).each do |cu| %>
            <tr>
              <td class="<%= "default-contact body-text15" if cu.is_company_contact?%>">
                <%if cu.invitation_accepted_at.nil?%>
                  <%= "#{cu.first_name} #{cu.last_name}" %>
                  <% if cu.invitation_created_at.present? && cu.invitation_accepted_at.blank? %>(Invited)<% end %>
                  <% if cu.title %>
                    <%= cu.title %></div>
                  <% end %>
                    <br>
                    <i class="icon-share reinvite-share li"></i>
                    <%= link_to("Re-invite",resend_invitation_path(cu.id), style: 'margin-left:24px;font-size: 13px')
                    %>
                <%else%>
                  <%= link_to company_user_path(cu.company, cu) do %>
                    <%= "#{cu.first_name} #{cu.last_name}" %>
                    <% if cu.invitation_created_at.present? && cu.invitation_accepted_at.blank? %>(Invited)<% end %>
                    <% if cu.title %>
                      <%= cu.title %></div>
                    <% end %>
                    <%end%>
                <%end%>
              </td>
              <td class="body-text1 b3">
                <% if cu.company_admin? or cu.admin? %>
                  A
                <% elsif cu.field_member? %>
                  F
                <% else %>
                  Staff
                <% end %>
              </td>
            </tr>
          <% end %>
          <% if (@company_users.respond_to? :total_pages) && @company_users.total_pages > 1 %>
            <tr>
              <td colspan="2">
                <%= paginate @company_users, :param_name => :c_page %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col s12 m12 l6">
    <div class="card-panel">
      <h1 class="card-panel-heading h1">Site Specific</h1>
      <table class="company_directory striped">
        <thead class="header-h3b b21">
          <tr>
            <th>Name</th>
            <th>Sites</th>
          </tr>
        </thead>
        <tbody>
          <% @project_users.order(:last_name).each do |cu| %>
            <tr>
              <td class="<%= "default-contact body-text15 lk1" if cu.is_company_contact?%>">
              <%= link_to company_user_path(cu.company, cu) do %>
                <span class="lk3"><%= "#{cu.first_name} #{cu.last_name}" %></span>
                <% if cu.invitation_created_at.present? && cu.invitation_accepted_at.blank? %>(Invited)<% end %>
                <% if cu.title %>
                  <br><span class="lk3"><%= cu.title %></span>
                <% end %>
              <% end %>
              <%if cu.invitation_accepted_at.nil?%>
                <br>
                <i class="icon-share reinvite-share"></i>
                <%= link_to("Re-invite",resend_invitation_path(cu.id,class: "lk1"), style: 'margin-left:24px;font-size: 13px')
                %>
              <%end%>
              </td>
              <td class="body-text1 b3">
                <%= render partial: "user_projects", locals: {user: cu,
                                                          project_assignments: cu.project_assignments.by_project_name} %>
              </td>
            </tr>
          <% end %>
          <% if (@project_users.respond_to? :total_pages) && @project_users.total_pages > 1 %>
            <tr>
              <td colspan="2">
                <%= paginate @project_users, :param_name => :p_page %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/companies/_form.html.erb
<%= simple_form_for(@company, html: {multipart: true}) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs row separator-row">
      <div class="col s12 m6 form-col">
        <div class="row">
          <%= f.input :name, autofocus: true, wrapper_html: {class: 'col s12'} %>
        </div>

        <div class="row">
          <%= f.association :contact, collection: @company.users, include_blank: false, wrapper_html: {class: 'col s12'} %>
        </div>

        <% if @company.company_logo.present? %>
            <div class="row">
              <div class="col s12">
                <%= image_tag current_user.company.company_logo.thumb.url %>
              </div>
            </div>
        <% else%>
            <div class="row">
              <div class="col s12">
                <%= image_tag("tennalogo/company-logo-not-uploaded.png") %>
              </div>
            </div>
        <% end %>

        <div class="row">
          <%= f.input :company_logo, as: :material_file, label: false, wrapper_html: {class: 'col s12'} %>
        </div>

        <% if @company.company_logo.present? %>
            <div class="row">
              <%= f.input :remove_company_logo, as: :boolean, boolean_style: :inline, wrapper_html: {class: 'col s12'} %>
            </div>
        <% end %>
      </div>

      <div class="col s12 m6 form-col">

        <%= f.simple_fields_for :address do |address_form| %>
            <%= render 'address/form', f: address_form %>
        <% end %>
      </div>
    </div>
  <div class="form-actions">
    <%= f.button :button, onClick: "ga('send', 'Internal Link', 'Companies: #{action_name}');".html_safe, data: {disable_with: 'Processing…'} %>
  </div>
<% end %>

app/views/companies/_user_projects.html.erb
<% if user.company_admin? || user.field_member? %>
  All sites
<% else %>
    <div class="collapsed">
    <% if project_assignments.count == 1 %>
      <%= project_name_and_role project_assignments.first %>
    <% elsif project_assignments.count > 1 %>
      Sites <a class="expander">( +<%= project_assignments.count %> )</a>
    <% else %>
      None
    <% end %>
    </div>
    <div class="other_projects">
      <% if  project_assignments.count > 1 %>
        <% project_assignments.each_with_index do |pa, i| %>
          <%= project_name_and_role pa %> <br/>
        <%  end %>
      <% end %>
    </div>
<% end %>

app/views/companies/edit.html.erb
<div class="card-panel">
  <div class="row">
    <div class="col s12">
      <div class="header-link">
        <h1 class="card-panel-heading h1">Edit Company</h1>
        <%= link_to_cancel %>
      </div>

      <%= render partial: 'form' %>
    </div>
  </div>
</div>

<%= fab @company %>

app/views/companies/show.html.erb
<div class="card-panel">
  <div class="row">
    <div class="col s12">
      <div><h5 class="company-name h1"><%= @company.name %></h5></div>
      <hr>
    </div>
  </div>

  <div class="row">
    <div class="col s6 m6 l6">
      <% if current_user.admin? %>
        <%= link_to 'Tenna Admin', admin_root_path, class: 'btn red' %>
        <br/>
      <% end %>
      <p class='body-text1 b9'>
        <%= @company.address.formatted_address %>
        <br>
        <span class='default-contact body-text15 b21'><%= @company.contact.name %></span>
        <br>
        <span class="lk1"><%= @company.contact.email %><%= @company.contact.phone_number %></span>
      </p>
      <% if can? :edit, @company %>
        <%= link_to 'Edit', edit_company_path(@company, back: request.fullpath), class: "lk1" %>
      <% end %>
    </div>

    <div class="col s6 m6 l6 right-align">
      <p class="margin-btm-none b9"><b class="h2">A:</b> Administrator</p>
      <p class="margin-btm-none b9"><b class="h2">F:</b> Field</p>
      <p class="margin-btm-none b9"><b class="h2">L:</b> Leader</p>
      <p class="margin-btm-none b9"><b class="h2">M:</b> Member</p>
    </div>
  </div>

  <div class="row">
    <div class="col s12 m6 l3 linkPermissionOver link-c lk1">
      <%= link_to '<ul><li class="txtPermission"><i class="fa fa-file-text-o"></i> Permissions Overview</li></ul>'.html_safe, 'https://s3.amazonaws.com/buildsourced-production-1/user_permissions.pdf', target: :_blank %>
    </div>
    <div class="col s12 m6 l9 btns-c">
      <% if current_user.company_admin? or current_user.admin? %>
        <%= link_to 'Assign Company Role', company_users_path(@company), class: 'waves-effect waves-light btn btn-company' %>
      <% end %>

      <% if current_user.company_admin? or current_user.admin? %>
        <%= link_to 'Invite New User', new_company_user_path(@company), class: 'waves-effect waves-light btn btn-company' %>
      <% end %>
    </div>

  </div>
</div>

<%= render partial: "directory" %>