config/routes.rb
Rails.application.routes.draw do
  resources :company_safety_configurations
  get 'safety_reports/landing_page'

  require 'sidekiq/web'

  mount Sidekiq::Web, at: '/sidekiq'
  mount ZapierRestHooks::Engine, at: '/hooks'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {invitations: 'invitations', registrations: 'registrations', passwords: 'passwords'}
  ActiveAdmin.routes(self)
  constraints DomainConstraint.new('bsqr1.com') do
    get '/:token', to: redirect { |path_params, req|
      "http://#{ENV['HOST']}/tracking_codes/#{path_params[:token]}"
    }
  end

  resources :tracking_codes do
    member do
      get :assign
      get :unassign
      get :unauthorized
    end
  end

  post 'tracking_ids/add_token', to: 'tracking_codes#add_token'

  #  zapier requests
  get '/zapier/sample_project', to: 'zapier#sample_project'
  get '/zapier/sample_video_view', to: 'zapier#sample_video_view'
  get '/zapier/sample_asset_reallocation', to: 'zapier#sample_asset_reallocation'
  get '/zapier/avaiable_on', to: 'zapier#sample_avaiable_on'
  get '/zapier/sample_maintenance', to: 'zapier#sample_maintenance_data'
  get '/zapier/sample_asset', to: 'zapier#sample_asset'
  get '/zapier/sample_marked_rental_or_public', to: 'zapier#sample_marked_rental_or_public'
  get '/zapier/sample_asset_remove_mp', to: 'zapier#sample_asset_remove_mp'
  get '/zapier/sample_route_stop', to: 'zapier#sample_route_stop'

  post '/zapier/create', to: 'zapier#create'
  post '/zapier/delete', to: 'zapier#destroy'

  get '/zapier/show', to: 'zapier#create_user'
  get '/lead/create', to: 'leads#create'
  post '/zapier/show', to: 'zapier#create_user'

  get '/zapier/update_hour_millage_asset', to: 'zapier#update_hour_millage_asset'
  post '/zapier/update_hour_millage_asset', to: 'zapier#update_hour_millage_asset'
  get '/zapier/update_lat_lng', to: 'zapier#update_lat_lng'
  post '/zapier/update_lat_lng', to: 'zapier#update_lat_lng'

  get 'assets/tokens', to: 'tracking_codes#get_tokens'
  post 'token/remove', to: 'tracking_codes#delete_token'
  post 'videos/add_video_usage', to: 'video_usages#add_video_usage'

  # Companies can only be created & deleted via /admin.
  resources :companies, only: [:show, :edit, :update] do
    resources :users, controller: 'company_assignments' do
      post :reinvite, to: 'company_assignments#reinvite_user'
      resources :project_assignments, controller: 'user_project_assignments', only: [:new, :create]
    end
  end

  get '/companies/:id/print_qr', to: 'companies#print_qr', as: 'print_company_qr'
  post '/companies/:id/qr_code_status', to: 'companies#qr_code_status', as: 'qr_code_status'
  post '/companies/:id/generate_printed_qr_codes', to: 'companies#generate_printed_qr_codes', as: 'generate_company_qr_codes'
  get '/companies/:id/download_printed_qr_codes', to: 'companies#download_printed_qr_codes', as: 'download_company_qr_codes'
  post '/companies/:id/email_printed_qr_codes', to: 'companies#email_printed_qr_codes', as: 'email_company_qr_codes'

  resources :projects, path: 'sites' do
    resources :assignments, controller: 'project_assignments', except: [:show, :edit]
    resources :csv_imports, controller: 'project_csv_imports', only: [:show, :create] do
      # No longer needed, as template is static; not generated dynamically anymore.
      # get :template, on: :collection
    end

    collection do
      post :upload_multiple
      get :search_by_name
    end
  end

  get '/assets/findit', to: 'assets#findit', :path => 'findit/inventory'
  get '/findit/checklist', to: 'assets#checklist'
  # get '/assets/get_assets_by_title', to: 'assets#get_assets_by_title'

  resources :assets do
    collection do
      put :update_multiple
      get :sold
      get :history_download
      get :search_by_title
    end

    member do
      patch :flag
      get :qr_scanning
      get :manage_inventory
      get :inventory_assets
      get :update_quantity
    end

    resources :marks, only: [:create, :destroy]
  end

  resources :groups do
    resources :csv_imports, controller: 'group_csv_imports', only: [:show, :create] do
    end
    collection do
      put :update_multiple
      post :upload_multiple
    end

    member do
      get :mark_as_closed
    end
  end
  resources :exports do
    collection do
      get :export_project
      get :export_assets
    end
  end

  resources :live_data, only: [:index] do
    collection do
      get :get_mqtt_token
      post :send_notification
      get '*path', action: :index
    end
  end

  resources :geo_fences do
  end

  resources :gauge_alerts do
    collection do
      get :search_assets_by_category
      get :category_assets
      get :asset_detail
      post :reset
    end
  end

  resources :exports, only: [:index, :show, :create]
  resources :news_items, only: [:index, :show], path: :newsroom

  get '/zip_validator' => 'maps#zip_validator', format: :json
  get '/zip_with_country_validator' => 'maps#zip_with_country_validator', format: :json
  get '/maps' => 'maps#index', :format => 'json'

  resources :wanted_assets, path: 'wanted', except: [:show] do
    collection do
      put :update_multiple
    end
  end

  post '/save_inventory', to: 'lists#save_inventory' , as: 'save_inventory'
  post '/save_checklist', to: 'lists#save_checklist' , as: 'save_checklist'
  get '/lists', to: 'lists#index' , as: 'lists'

  post '/get_asset', to: 'assets#asset'
  post 'reports/assets/generate', to: 'reports#generate_project_assets_report', as: 'reports_generate_project_assets_report'
  post 'reports/asset_location_audit/generate', to: 'reports#generate_asset_location_audit_report', as: 'reports_generate_asset_location_audit_report'
  get 'reports/:project_id/project_assets', to: 'reports#project_assets_report' , as: 'reports_project_assets_report'
  get 'reports', to: 'reports#index' , as: 'reports'
  #get 'csv_analytics', to: 'asset_reports#csv_analytics' , as: 'csv_analytics'

  get 'reports/assets', to: 'asset_reports#index', as: 'asset_reports'
  post 'reports/assets/filters', to: 'asset_reports#filter_post', as: 'asset_report_filter_post'
  get 'reports/assets/delete_myfilter/:id', to: 'asset_reports#delete_myfilter', as: 'asset_report_filter_delete'
  patch 'reports/assets/filters/:id', to: 'asset_reports#filter_patch', as: 'asset_report_filter_patch'
  get 'reports/assets/filters/:id', to: 'asset_reports#filter_get', as: 'asset_report_filter_get'
  get 'reports/assets/pre_filters/:key', to: 'asset_reports#pre_filter_get', as: 'asset_report_pre_filter_get'
  get 'reports/assets/download', to: 'asset_reports#download', as: 'asset_reports_download'
  patch 'reports/assets/filter_labels/:id', to: 'asset_reports#filter_label_patch', as: 'asset_report_filter_label_patch'
  post 'reports/assets/filter_labels', to: 'asset_reports#filter_label_post', as: 'asset_report_filter_label_post'

  get '/assets/:id/log_in', to: 'assets#log_in'
  get '/assets_versions/create'
  get '/user/profile' => 'profile#index'
  get '/dashboard' => 'dashboard#index'
  get '/marketplace' => 'marketplace#index'
  get '/favorites' => 'favorites#index'

  post '/update_cookies' => 'pages#update_cookies'

  get '/contact_us' => 'pages#contact_us'
  get '/terms' => 'pages#terms'
  get '/infringement_notice' => 'pages#infringement_notice'
  get '/privacy_policy' => 'pages#privacy_policy'
  get '/learn_more' => 'pages#learn_more'
  get '/market_place' => 'pages#market_place'
  get '/value' => 'pages#value'
  get '/industries_served' => 'pages#industries_served'
  get '/support' => 'pages#support'
  get '/learn_more' => 'pages#learn_more'
  get '/about_us' => 'pages#about_us'
  get '/reverse_geocode_map' => 'projects#reverse_geocode_map'

  post '/learn_more_mail' => 'pages#learn_more_email'
  post '/leads_mailer_mail' => 'pages#leads_mailer_email'

  # root 'pages#index'
  if Rails.env.development? || Rails.env.test?
    root to: 'pages#index'
  elsif Rails.env.staging? || Rails.env.production?
    root to: 'dashboard#index'
  end

  get '/robots', to: redirect('/robots.txt'), format: false
  get '/robots.:format' => 'robots#index'
  get '/resend_invitation' => 'companies#resend_invitation'
  resources :geo_positions, only: [:index]
  resources :clusters, only: [:index]
  resources :analytics, only: [:create] do
    collection do
      post :assets_filters
      post :asset_daily_filter
      post :more_most_recent
      post :asset_hour_filter
      post :asset_most_recent_filter
      get :search_groups_by_name
      get :search_users_by_name
      get :get_categories
      get :get_subcategories_by_category_id
      get :get_token_types
      get :get_analytic_filter_labels
    end
  end
  resources :map, only: [:index]

  resources :path_finder, only: [:index, :show, :create, :update] do
    get :show_multi, on: :collection
    post :route_history_search, on: :collection
    get :manage_routes, on: :collection
    # get :preview, on: :member
  end

  get '/route/:id/:fired_date', to: 'path_finder#show', as: 'route'
  get '/route_multi/:ids', to: 'path_finder#show_multi'
  get '/routes/search_by_name', to: 'path_finder#search_by_name'
  post '/path_finder/mark_as_done', to: 'path_finder#mark_as_done'
  post '/path_finder/mark_as_undone', to: 'path_finder#mark_as_undone'
  post '/path_finder/mark_all_as_undone', to: 'path_finder#mark_all_as_undone'
  post '/path_finder/send_route', to: 'path_finder#send_route'
  post '/path_finder/waypoint_options', to: 'path_finder#waypoint_options'
  post '/path_finder/project_assets/:id', to: 'path_finder#project_assets'
  post '/path_finder/:route_slug/:fired_date/preview', to: 'path_finder#preview', as: 'preview'
  get '/path_finder/:id/:fired_date/edit', to: 'path_finder#edit', as: 'path_finder_edit'
  get '/events', to: 'events#index', as: 'event_index'
  get '/events/db_action', to: 'events#db_action', as: 'event_action'
  get '/events/asset/:asset_id', to: 'events#index', as: 'event_asset'

app/models/report.rb
class Report 

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :company_reports_subscription
  def index
    @filter_search = ReportAssetsSearch.new

    filterable_projects = FilterableProjects.new(
      user: current_user,
      search_options: {company: current_user.company},
      params:{},
      zip_code: cookies[:zip_code]
    )
    projects = filterable_projects.projects.per(10000)
    @projects = projects.collect{|project| [project[:name],project[:id]] if project}.compact if projects.present?
  end

  def generate_project_assets_report
    unless params[:report_assets_search][:project].present?
      params[:report_assets_search][:project] =  params[:report_assets_search][:projects]
    end
    filterable_assets = FilterableReportAssets.new(
      user: current_user,
      params: params,
      zip_code: cookies[:zip_code]
    )

    @assets_versions = filterable_assets.report_project_assets_and_reallocations
    @asset_versions_with_total_days_of_assets_on_project = AssetsVersion.asset_versions_with_total_days_of_assets_on_project(@assets_versions)
    project_id = params[:report_assets_search][:project]
    @project = Project.find project_id
    @assets_count = @project.assets.where.not(state: ['deleted', 'sold']).count
    datestamp = DateTime.now.strftime('%m-%d-%Y')
    @internal_rental_rate =  params[:report_assets_search][:internal_rental_rate]
    @calculate_cost = params[:report_assets_search][:calculate_cost]  

    if @internal_rental_rate == "1"
      @internal_rental_rate = true
    else
      @internal_rental_rate = false
    end

    @calculate_cost = ( @calculate_cost == "1" ? true : false) 

    if params[:report_assets_search][:export_type] == 'csv'
      file_path = AssetsVersion.generate_csv_for_project_assets_report(@asset_versions_with_total_days_of_assets_on_project, @assets_versions, current_user, @project.name,@internal_rental_rate, @calculate_cost)
      send_file file_path, :type => 'application/zip', :x_sendfile => true, filename: "#{@project.name}-Assets-#{datestamp}.zip"
    elsif params[:report_assets_search][:export_type] == 'pdf'
      @asset = AssetsVersion.new
      @datetime = DateTime.now
      leaders_count = @project.project_assignments.where(role:0).count
      members_count = @project.project_assignments.where(role:1).count
      @team_members = { leaders:leaders_count, members:members_count }
      asset_search = AssetSearch.new
      @assets_value = asset_search.cost_and_value(project_id)

      pdf = render_to_string pdf: "#{@project.name}-Assets-#{@datetime.strftime('%m-%d-%Y')}.pdf",
            template: 'reports/generate_project_assets_report.html.erb',
            orientation: 'Landscape',
            page_size: 'A4',
            :margin => {:top => 20, :bottom =>37 },
            header: {html: {template: 'reports/header.pdf.erb',
                                     locals:{project_name: @project.name,date: @datetime.strftime("%m/%d/%Y")}},
                                     :spacing => 15
                                     },
            :footer => {
              :content => render_to_string('reports/footer.pdf.erb'),
              :spacing => 0
            }
      send_data(pdf,
         :filename    => "#{@project.name}-Assets-#{@datetime.strftime('%m-%d-%Y')}.pdf",
         :disposition => 'attachment')
    end
    CompaniesVersion.create!(field_name: 'site utilization', from: '', to: "#{params[:report_assets_search][:export_type]}",
                             whodunnit: current_user.try(:id), company_id: current_user.company.try(:id), action: 'download')
  end

  def generate_asset_location_audit_report
    params[:report_assets_search][:asset_categories] = params[:report_assets_search][:asset_categories].reject(&:empty?)
    params[:report_assets_search][:projects] =  params[:report_assets_search][:projects].reject(&:empty?)

    asset_location_audit_by_category = params[:report_assets_search][:asset_category_filter] == '1'
    asset_location_audit_by_project = params[:report_assets_search][:project_filter] == '1'

    filterable_assets = FilterableReportAssets.new(
      user: current_user,
      params: params,
      zip_code: cookies[:zip_code]
    )

    @datetime = DateTime.now
    audit_report = {project: {}, category:{}}
    both_reports_flag = (asset_location_audit_by_category and  asset_location_audit_by_project)
    if asset_location_audit_by_project || asset_location_audit_by_category
      if params[:report_assets_search][:projects].count > 0 || asset_location_audit_by_project || both_reports_flag
        @assets_grouped_by_proj, @location_match_mismatch, @location_match_total_by_proj, @location_mismatch_total_by_proj, @projects_names, @location_versions_by_proj = filterable_assets.asset_location_audit_by_project(current_user,cookies[:zip_code], both_reports_flag)
        audit_report[:project][:template] = 'reports/generate_asset_location_audit_report_by_project.html.erb'
        audit_report[:project][:filename] = "Asset-Location-Audit-By-Project-#{ @datetime.strftime('%m-%d-%Y') }"

      elsif params[:report_assets_search][:asset_categories].count > 0 || asset_location_audit_by_category
        @assets_grouped_by_category, @location_match_total_by_cat, @location_mismatch_total_by_cat, @location_versions_by_cat  = filterable_assets.asset_location_audit_by_category(current_user)
        audit_report[:category][:template] = 'reports/generate_asset_location_audit_report_by_category.html.erb'
        audit_report[:category][:filename] = "Asset-Location-Audit-By-Category-#{@datetime.strftime('%m-%d-%Y')}"
      end
    end

    @user = current_user
    @browser_timezone = browser_timezone

    final_files = {project: {}, category: {} }
    audit_report.each do |key,val|
      if val.present?
        final_files[key][:filename] = val[:filename]
        pdf = render_to_string pdf: "#{val[:filename]}.pdf",
              template: val[:template],
              orientation: 'Landscape',
              page_size: 'A4',
              show_as_html: true,
              :margin => {:top => 20, :bottom =>37 },
              header: {html: {template: 'reports/asset_location_audit_report_header.pdf.erb',
                                       locals:{date: @datetime.strftime('%m/%d/%Y'), asset_location_audit_by_project: asset_location_audit_by_project, asset_location_audit_by_category: asset_location_audit_by_category, both_reports_flag: both_reports_flag }},
                                       :spacing => 15
                                       },
              :footer => {
                :content => render_to_string('reports/footer.pdf.erb'),
                :spacing => 0
              }
        final_files[key][:pdf] = pdf
      end
    end

    if final_files[:project].present?
      pdf_file = final_files[:project][:pdf]
      file_name = final_files[:project][:filename]
    elsif final_files[:category]
      pdf_file = final_files[:category][:pdf]
      file_name = final_files[:category][:filename]
    end

  send_data(pdf_file,
            :filename    => "#{file_name}.pdf",
            :disposition => 'attachment')

  CompaniesVersion.create!(field_name: 'asset location audit', from: '', to: 'pdf',
                             whodunnit: current_user.try(:id), company_id: current_user.company.try(:id), action: 'download')
  end

  def project_assets_report
    @project = params[:project_id]
    @filter_search = ReportAssetsSearch.new
  end

  def company_reports_subscription
    if current_user.company
      company = current_user.company
      @company_reports_subscription = company.subscriptions.where(category: 'company reports',state: 'active',payment: true).first
    end
  end
end

app/views/reports/_asset_location_audit.html.erb
<div  class="tab-content" style="padding:0px;" id="asset-location-audit">
  <div  class="" >
    
    <ul class="collapsible" data-collapsible="expandable">
      <li>
        <div class="collapsible-header active h1">Asset Location Audit
          <!-- <i class="material-icons right more report-info-i-more">expand_more</i> -->
        </div>
        <div class="collapsible-body">
        <div class="b21">Report Information</div>
        <p class="b1">Asset location audit report provides a comparison of the current location of assets and their sites allocations. This allows you to quickly audit the locations of assets and take action.</p></div>
      </li>
    </ul>

    <div style="padding: 0px 16px 16px 16px;">
      <div class="asset-report-header">
        <div class="header-link">
        </div>
      </div>

      <div>
        <%= simple_form_for(@filter_search, url: reports_generate_asset_location_audit_report_path(format: :pdf), method: :post) do |f| %>
          <div class="asset-report-body row">
            <div class="col s12 m12 " style="margin-bottom:16px;">
              <label style="font-size: 1rem;">Select Report By: </label>
            </div>
            <div class="col m12 s12 l12" style="padding-left:32px;">
              <div class="export-assets-report row">
                <div class="col s12 m12">
                  <%= f.input :asset_category_filter, label: 'Asset Category', as: :boolean, boolean_style: :inline, input_html: {class: 'filled-in' , id: 'asset-category-filter'} %>
                </div>

                <div class="col s12 m12 report-category-types">
                  <%= f.input :equipment, as: :boolean, boolean_style: :inline, input_html: {class: 'filled-in', id: 'report_filter_search_equipment'} %>
                </div>

                <div class="col s12 m12 report-category-types">
                  <%= f.input :material, as: :boolean, boolean_style: :inline, input_html: {class: 'filled-in' , id: 'report_filter_search_material'}%>
                </div>

                <div class= "col s11 m11 category-filters">
                  <%= f.input :asset_categories, label: false , input_html: { class: 'select2', multiple: true }, collection: Category.with_type('material').by_name, include_blank: false, wrapper_html: {class: 'col s12 m12 report-assets-material-categories' , style: 'padding-left:32px;'} %>
                  <%= f.input :asset_categories, label: false, input_html: { class: 'select2', multiple: true }, collection: Category.with_type('equipment').by_name, include_blank: false, wrapper_html: {class: 'col s12 m12 report-assets-equipment-categories' , style: 'padding-left:32px;'} %>
                  <%= f.input :asset_categories, label: false, input_html: { class: 'select2', multiple: true }, collection: Category.by_name, include_blank: 'All Categories', wrapper_html: {class: 'col s12 m12 report-assets-all-categories' , style: 'padding-left:32px;'} %>
                </div>
              </div>

              <div class="export-assets-report row">
                <div class="col s12 m12">
                  <%= f.input :project_filter, label: 'Site', as: :boolean, boolean_style: :inline, input_html: {class: 'filled-in', id: 'project-filter'} %>
                </div>

                <div class= "col s11 m11">
                  <%= f.input :projects, label: false, input_html: { class: 'select2', multiple: true ,id: 'projects-collection'}, collection: @projects, include_blank: 'All Sites', wrapper_html: {class: 'col s12 m12', style: 'padding-left:32px;'} %>
                </div>
              </div>

              <div class="row export-assets-report">
                <div class="col s2 m2" style= "font-size: 1rem;">
                  <label>Date Range: </label>
                </div>
                <div class="col s9">
                  <input type="date" class="date-range datepicker report-date col m6 ip2" name="report_assets_search[date_from]" placeholder="From" max= <%= Date.today.to_s %> >
                  <input type="date" class="date-range datepicker report-date col m6 ip2" name="report_assets_search[date_to]" placeholder="To" max= <%= Date.today.to_s %> >
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col m9 s12">
              <p class="center-align red-text multi-projects-msg">This report may take up to a minute to produce.</p>
              &nbsp;&nbsp;
            </div>

            <div class="row" style="float:right; margin:10px;">
              <button name="button" type="submit" class="waves-effect waves-light btn but1">Create Report</button>
              <%#= f.button :submit, 'Create Report', {class: 'waves-effect waves-light btn but1'} %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reports/_project_utilization.html.erb
<div  class="tab-content" style="padding:0px;" id="project-utilization">
  <div  class="">
    <ul class="collapsible" data-collapsible="expandable">
      <li>
        <div class="collapsible-header active h1">Report Information
          <!-- <i class="material-icons right more report-info-i-more">expand_more</i> -->
        </div>
        <div class="collapsible-body">
        <div class="b21">Site Utilization</div>
        <p class="b1">Site utilization report provides a summary list of all the assets that have been allocated to the site including details on arrival to and departure from the site, total days on site, and total value. This allows you to compare your asset allocation against internal billing systems and to gain insights into the utilization of your assets across operations.</p></div>
      </li>
    </ul>

    <div style="padding: 0px 16px 16px 16px;">
      <div class="asset-report-header">
        <div class="header-link">
        </div>
      </div>

      <div>
        <%= simple_form_for(@filter_search, url: reports_generate_project_assets_report_path(format: :pdf), method: :post) do |f| %>
          <div class="asset-report-body row">
            <div class="col m12 s12 l12">
              <div class="export-assets-report row">
                <div class="col l2 s3 m3 sort-order-label subh2">Site: </div>
                  <%= f.input :projects, label: false, input_html: { class: 'select2  dd1' }, collection: @projects, wrapper_html: {class: 'col s9 m9 l9 dd1'} , include_blank: false %>
              </div>

              <div class="row">
                <div class="col s3 m3 l2 sort-order-label subh2">Sort Order: </div>

                <%= f.input :sort_order, label: false, input_html: { class: 'sort-order-input select2' }, collection: ['Asset Id', 'Asset Title'], :selected => 'Asset Id', wrapper_html: {class: 'sort-order col s8 m5 l7  dd1'} %>
              </div>

              <div class="row export-assets-report">
                <div class="col s3 m3 l2 subh2">Date Range: </div>
                <div class="col s8 m8 l9">
                  <input type="date" class="date-range datepicker report-date col m6 l6 ip2" name="report_assets_search[date_from]" placeholder="From" max= <%= Date.today.to_s %> >
                  <input type="date" class="date-range datepicker report-date col m6 l6 ip1" name="report_assets_search[date_to]" placeholder="To" max= <%= Date.today.to_s %> >
                </div>
              </div>

              <div class="row">
                <div class="col s3 m3 l2 subh2">Include in Report: </div>
                <div class="col s8 m8 l9">
                  <%= f.input :internal_rental_rate, as: :boolean, boolean_style: :inline, input_html: {class: 'filled-in'}, wrapper_html: {class: 'col m6 l4 ip2'},label_html: {class: 'cb1'} %>
                  <%= f.input :calculate_cost, as: :boolean, boolean_style: :inline,label: "Calculate cost to job &nbsp;&nbsp; <span style='font-style: italic;font-size: 12px;'>[Days on project * price]</span>".html_safe, input_html: {class: 'filled-in'}, wrapper_html: {class: 'col m6 l8 ip2'},label_html: {class: 'cb1'} %>
                </div>
              </div>

              <div class="export-type row export-assets-report">
                <div class="export-as-label col s3 m3 l2 subh2">Export as:</div>
                <div class="export-types col s8 m8 l6" >
                  <%= f.collection_radio_buttons :export_type, [['csv', 'CSV'] ,['pdf', 'PDF']], :first, :last, wrapper_html: {class: 'export-type checkbox'}, :checked => 'csv' %>
                </div>
              </div>

              <div>
                <%= f.input :project, :as => :hidden , input_html: {value: @project}%>
              </div>
            </div>
          </div>

          <div class="row" style="float:right;margin:10px;">
            <button name="button" type="submit" class="waves-effect waves-light btn but1">Create Report</button>
            <%#= f.button :submit, '', {class: 'waves-effect waves-light btn'} %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reports/project_assets_report.html.erb
<div class="card-panel">
  <div class="row">
    <div class="asset-report-header">
      <div class="header-link">
        <h1 class="h1 without-border modal-heading-botm"><b>Export Asset Report</b></h1>
        <%= link_to "Back".html_safe, project_path(@project), class: 'lk1' %>
      </div>
    </div>
    <%= simple_form_for(@filter_search, url: reports_generate_project_assets_report_path(format: :pdf), method: :post) do |f| %>
      <div class="asset-report-body row">
        <div class="col s12 m8">
          <div class="export-assets-report row">
            <div class="col s3 m3 sort-order-label"><label class="subh2">Sort Order: </label></div>
            <%= f.input :sort_order, label: false, input_html: { class: 'sort-order-input dd1' }, collection: ['Asset Id', 'Asset Title'], :selected => 'Asset Id', wrapper_html: {class: 'sort-order col s5 m5'},input_html: {class: 'dropdown_fix'} %>
          </div>
          <div class="row export-assets-report">
            <div class="col s3 m3"><label class="subh2">Date Range: </label></div>
            <div class="col s9">
              <input type="date" class="date-range datepicker report-date" name="report_assets_search[date_from]" placeholder="From" max= <%= Date.today.to_s %> >
              <input type="date" class="date-range datepicker report-date" name="report_assets_search[date_to]" placeholder="To" max= <%= Date.today.to_s %> >
            </div>
          </div>

          <div class="export-type row export-assets-report">
            <div class="export-as-label col s3 m3"><label class="subh2">Export as:</label></div>
            <div class="export-types col s6 m6" >
              <%= f.collection_radio_buttons :export_type, [['csv', 'CSV'] ,['pdf', 'PDF']], :first, :last, wrapper_html: {class: 'export-type'}, :checked => 'csv' , label_html: {class: 'cb1'}%>
            </div>
          </div>

          <div><%= f.input :project, :as => :hidden , input_html: {value: @project}%></div>

        </div>
        <div class="col m4"></div>
      </div>

      <div class="row" style="float:right;margin:10px;">
        <%= link_to 'Cancel', project_path(@project), {class: 'btn asset-report-btn'} %>
        <%= f.button :submit, 'Export', {class: 'waves-effect waves-light btn'} %>
      </div>
    <% end %>
  </div>
</div>